name: Deploy STG

on:
  push:
    branches:
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
          docker build --build-arg VERSION=${GITHUB_REF##*/} -t test .
          echo "$(docker run test)"
